/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpa.views;
import tpa.app.ComparadorLivrosPorNome;
import tpa.app.GeradorDeArvores;
import arvores.lib.ArvoreAVL;
import arvores.lib.IArvoreBinaria;
import assets.lib.Livro;
import graphos.lib.Grapho;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author breno
 */
public class Arvores extends javax.swing.JFrame {
    public Insert insert_viewer;
    public String arvoreMontada;
    public Init inicio_viewer;
    public Livro livros;
    private List<Livro> listaLivros = new ArrayList<>();
    public IArvoreBinaria<Livro> arv;

    /**
     * Creates new form SistemaAcademico
     */
    public Arvores() {
        initComponents();
        this.setLocationRelativeTo(null);
        listaLivros = livros.carregaLivros();

        GeradorDeArvores gerador = new GeradorDeArvores();
        ComparadorLivrosPorNome comparador = new ComparadorLivrosPorNome();
        arv = (IArvoreBinaria<Livro>) new ArvoreAVL(comparador);
        gerador.geraArvoreDegenerada(listaLivros, arv);
        System.out.println("Árvore AVL Criada");
        System.out.println("Quantidade de Nós: " + arv.quantidadeNos()+ " Altura: " + arv.altura());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisualizaArvore = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DemonstracaoArvore = new javax.swing.JEditorPane();
        VisualizaLista = new javax.swing.JButton();
        ExcluirLivro = new javax.swing.JButton();
        AdicionarLivro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PainelConsulta = new javax.swing.JEditorPane();
        ConsultaLivro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        MinhasIndicacoes = new javax.swing.JButton();

        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        VisualizaArvore.setText("Visualiza Arvore");
        VisualizaArvore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisualizaArvoreMouseClicked(evt);
            }
        });
        VisualizaArvore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizaArvoreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel2.setText("Estante de Livros");

        jButton1.setText("< Voltar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(DemonstracaoArvore);

        VisualizaLista.setText("Visualiza Lista");
        VisualizaLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisualizaListaMouseClicked(evt);
            }
        });

        ExcluirLivro.setText("Excluir Livro");

        AdicionarLivro.setText("Adicionar Livro");

        jScrollPane1.setViewportView(PainelConsulta);

        ConsultaLivro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Escolha o livro a consultar");

        MinhasIndicacoes.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        MinhasIndicacoes.setText("Minhas Indicacoes");
        MinhasIndicacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinhasIndicacoesMouseClicked(evt);
            }
        });
        MinhasIndicacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinhasIndicacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(VisualizaArvore)
                .addGap(18, 18, 18)
                .addComponent(VisualizaLista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExcluirLivro)
                                    .addComponent(AdicionarLivro)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(ConsultaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(MinhasIndicacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(MinhasIndicacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VisualizaArvore, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisualizaLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExcluirLivro)
                        .addGap(28, 28, 28)
                        .addComponent(AdicionarLivro)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ConsultaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void VisualizaArvoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizaArvoreMouseClicked
        try {
            
         
//            arv.popularJTextAreaImages(DemonstracaoArvore,listaLivros);
            arvoreMontada =  arv.imprimirArvore();

        } catch (Exception e) {
            System.out.println("Quantidade de Nós: " +e);

        }
        DemonstracaoArvore.setContentType("text/plain");

        DemonstracaoArvore.setText(arvoreMontada);
    }//GEN-LAST:event_VisualizaArvoreMouseClicked

    private void VisualizaArvoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizaArvoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisualizaArvoreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        inicio_viewer = new Init();
        inicio_viewer.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void VisualizaListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisualizaListaMouseClicked
        // TODO add your handling code here:
        arv.popularJTextAreaImages(DemonstracaoArvore,listaLivros);

    }//GEN-LAST:event_VisualizaListaMouseClicked

    private void MinhasIndicacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinhasIndicacoesMouseClicked

    }//GEN-LAST:event_MinhasIndicacoesMouseClicked

    private void MinhasIndicacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinhasIndicacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinhasIndicacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arvores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arvores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arvores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arvores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arvores().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarLivro;
    private javax.swing.JComboBox<String> ConsultaLivro;
    private javax.swing.JEditorPane DemonstracaoArvore;
    private javax.swing.JButton ExcluirLivro;
    private javax.swing.JButton MinhasIndicacoes;
    private javax.swing.JEditorPane PainelConsulta;
    private javax.swing.JButton VisualizaArvore;
    private javax.swing.JButton VisualizaLista;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
